// Copyright (c) 2024 foxsofter.
//
// Do not edit this file.
//

import 'package:flutter_thrio/flutter_thrio.dart';

import 'flutter5.page.dart';

class Module with ThrioModule, ModulePageBuilder, ModuleRouteBuilder {
  @override
  String get key => 'flutter5';

  @override
  void onPageBuilderSetting(final ModuleContext moduleContext) =>
      pageBuilder = (settings) => Flutter5Page(
            moduleContext: moduleContext,
            settings: settings,
          );

  @override
  void onRouteBuilderSetting(ModuleContext moduleContext) {
    routeBuilder = (pageBuilder, settings) {
      return NavigatorPresentRoute(
        pageBuilder: pageBuilder,
        settings: settings,
        barrierDismissible: true,
        fullscreenDialog: true,
      );
    };
  }
}
